//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvhBaiKiemTraGK.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvhKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nvhKhoa()
        {
            this.nvhSinhVien = new HashSet<nvhSinhVien>();
        }
    
        public string NvhMaKH { get; set; }
        public string NvhTenKH { get; set; }
        public Nullable<bool> NvhTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nvhSinhVien> nvhSinhVien { get; set; }
    }
}
