//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvhBaiKiemTraGK.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NvhK22CNT4Lesson07dbEntities4 : DbContext
    {
        public NvhK22CNT4Lesson07dbEntities4()
            : base("name=NvhK22CNT4Lesson07dbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nvhKhoa> nvhKhoa { get; set; }
        public virtual DbSet<nvhSinhVien> nvhSinhVien { get; set; }
    }
}
