//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvhBaiKiemTraGK.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvhSinhVien
    {
        public string NvhMaSv { get; set; }
        public string NvhHoSV { get; set; }
        public string NvhTenSV { get; set; }
        public Nullable<System.DateTime> NvhNgaySinh { get; set; }
        public Nullable<bool> NvhPhai { get; set; }
        public string NvhPhone { get; set; }
        public string NvhEmail { get; set; }
        public string NvhMaKh { get; set; }
    
        public virtual nvhKhoa nvhKhoa { get; set; }
    }
}
