//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvhK22CNT4Lesson11_2210900102.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NvhCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NvhCategory()
        {
            this.NvhProduct = new HashSet<NvhProduct>();
        }
        
        [Display(Name= "Mã danh mục ")]
        public int NvhId { get; set; }
        [Display(Name = "Tên danh mục ")]
        public string NvhCateName { get; set; }
        [Display(Name = "Trạng thái ")]
        public Nullable<bool> NvhStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NvhProduct> NvhProduct { get; set; }
    }
}
