//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvh_Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvhAccount
    {
        public int NvhID { get; set; }
        public string NvhUserName { get; set; }
        public string NvhPassword { get; set; }
        public string NvhFullName { get; set; }
        public string NvhEmail { get; set; }
        public string NvhPhone { get; set; }
        public Nullable<bool> NvhActive { get; set; }
    }
}
